train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/ssd_data/projects/ContinuousSR/data/1_Image_SR/DIV2K/DIV2K_train_HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled 
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 64

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/ssd_data/projects/ContinuousSR/data/1_Image_SR/DIV2K/DIV2K_valid_HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 64


data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: my-gauss-simple
  args:
    encoder_spec:
      name: swinir
      args: 
        no_upsampling: true  

optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 2000
 
lr_schedule:
   name: CosineAnnealingLR 
   args:
     T_max: 2000 
     eta_min: 1.e-6

epoch_val: 1
epoch_save: 100

pre_train: ~