train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/ssd_data/projects/ContinuousSR/data/Toy/HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled 
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 1

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/ssd_data/projects/ContinuousSR/data/Toy/HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 1

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: grape-enc-gs4
  args:
    encoder_spec:
      name: gs-enc-baseline
      args:
        base: 64
        n_feats: 256 
 
optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 100000
 
lr_schedule:
   name: CosineAnnealingLR 
   args:
     T_max: 100000 
     eta_min: 1.e-6

epoch_val: 1
epoch_save: 100

pre_train: ~