train_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/projects/GRAPE/data/DIV2K/DIV2K_train_HR
      repeat: 20
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled 
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 16

val_dataset:
  dataset:
    name: image-folder
    args:
      root_path: /home/jijang/projects/GRAPE/data/DIV2K/DIV2K_valid_HR
      cache: in_memory
  wrapper:
    name: sr-implicit-downsampled
    args:
      inp_size: 256
      scale_max: 4
      scale_min: 4
  batch_size: 16

data_norm:
  inp: {sub: [0], div: [1]}
  gt: {sub: [0], div: [1]}

model:
  name: grape_4hw
  args:
    encoder_spec:
      name: edsr-baseline
      args:
        no_upsampling: false
        scale: 4
 
optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 1000
 
lr_schedule:
   name: CosineAnnealingLR 
   args:
     T_max: 1000 
     eta_min: 1.e-6

epoch_val: 1
epoch_save: 100

pre_train: ~